services:
  mysql:
    image: mysql:8
    container_name: mysql_prode
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prode
    ports:
      - "3306:3306"
    volumes:
      - ./prode.sql:/docker-entrypoint-initdb.d/prode.sql